name: DocBoxFurnace
main: com.almramc.assemblylinefurnace.AssemblyFurnace
version: 1.2
permissions:
    docboxfurnace.use:
        description: enabled users to use DocBoxFurance
        default: false
    