name: DocBoxFurnace
main: me.znickq.assemblyfurnace.AssemblyFurnace
version: 1.2
permissions:
    docboxfurnace.use:
        description: enabled users to use DocBoxFurance
        default: false
    