name: AssemblyLineFurnace
main: com.almramc.assemblylinefurnace.AssemblyFurnace
version: 1.0
permissions:
    assemblylinefurnace.use:
        description: enabled users to use Assembly Line Furnace.
        default: false
    